spring:
  application:
    name: ums-admin-provider-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.168.208;database=Rental
    username: sa
    password: 1234abcd.
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#dubbo:
#  scan:
#    base-packages: com.funtl.myshop.plus.provider.service #服务暴露与发现消费所在的package
#  protocol:#协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
#    name: dubbo
#    port: -1
#    serialization: kryo
#  registry:#注册中心配置，用于配置连接注册中心相关信息。
#    address: nacos://nacos.funtl.com
#    port: 80

dubbo:
  scan:
    base-packages: com.funtl.myshop.plus.provider.service #服务暴露与发现消费所在的package
  registry: #注册中心配置，用于配置连接注册中心相关信息。
    address: nacos://127.0.0.1
    port: 8848
  protocol: #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo
    port: -1
    serialization: kryo

mybatis:
  type-aliases-package: com.funtl.myshop.plus.provider.domain
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8001
